import textbox
import time
import os
testbox = textbox.box()
testbox.addtext("This is a test of the textbox.py module.")
testbox.addtext("la de da do this is a test")
testbox.print()
testbox = textbox.box()
testbox.addtext("This is a test of the textbox.py module.")
testbox.addtext("la de da do this is a test")
testbox.addtext("This is a very long line that will be wrapped.")
testbox.addtext("Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.")
testbox.print()
testbox = textbox.box()
testbox.addtext("This is a test of the textbox.py module.")
testbox.addtext("la de da do this is a test")
testbox.addtext("This is a very long line to test word wrapping with zero spaces.")
testbox.addtext("12345678910111213141516171819202123242526272829348190481409179047109847901387409837091483709871093487094871098734109870398279084")
testbox.print()
testbox = textbox.box()
testbox.addtext("This is a test of the textbox.py module.")
testbox.addtext("la de da do this is a test")
testbox.addtext("This is a very long line to test word wrapping with one space at the start.")
testbox.addtext("This currently has a kind of dogey solution, but it works.")
testbox.addtext("long line12345678910111213141516171819202123242526272829348190481409179047109847901387409837091483709871093487094871098734109870398279084")
testbox.print()
testbox = textbox.box(full=True)
testbox.addtext("This tests the box being full, even with a little text")
testbox.print()
testbox = textbox.box(margin=5, full=True)
testbox.addtext("this test has the full flag and a margin of 5")
testbox.addtext("Hello World")
testbox.print()
testbox = textbox.box(margin=5, full=True)
testbox.addtext(f"The current time is {time.ctime()}, and the current working directory is {os.getcwd()}")
testbox.print()
testbox = textbox.box(margin=5, full=True, drawers=textbox.BLOCKDRAWERS)
testbox.addtext("This is a text box with block sides")
testbox.addtext("this looks weird imo")
testbox.print()
testbox = textbox.box(margin=5, full=True, drawers=textbox.SINGLEDRAWERS)
testbox.addtext("This is a text box with single line sides")
testbox.print()
testbox = textbox.box(margin=5, full=True, drawers=textbox.THINDRAWERS)
testbox.addtext("This is a text box with SKINNY SIDES")
testbox.addtext("this made me add 2 sides for top and bottom lol")
testbox.print()
testbox = textbox.box(margin=5, full=True, drawers=textbox.OUTWARDTHINDRAWERS)
testbox.addtext("This is a text box with OUTWARD SKINNY SIDES")
testbox.addtext("this made me add 2 sides for top and bottom lol")
testbox.print()
testbox = textbox.box(margin=5, full=True)
testbox.addtext("You can also change the default drawers by using textbox.defaultdrawers = new drawers")
testbox.print()
textbox.defaultdrawers = textbox.THINDRAWERS

testbox = textbox.box(margin=5, full=True)
testbox.addtext("This is a text box with thin block sides, because the default drawers have been changed")
testbox.print()
testbox = textbox.box()
testbox.addtext("This was initaly only for phwd, but I havent seen anyone else make something like this.")
testbox.addtext("I might release it standalone without phwd, but I havent decided yet.")
testbox.addtext("I am planning to also add more advanced features to it, but how I'm going to do that is unknown to me.")
testbox.addtext("I also might add things like justifying text so the weirdness of doing that is hidden but this may not be possible the way I would want it to be.")
testbox.addtext("I am planning for this to be relatively lightweight module, so that it can be easily used in basic programs, not worthy of creating a GUI.")
testbox.addtext("This may also be updated to work with curses, but I have never used curses before so it might be a while til it uses it.")
testbox.addtext("Also unfortunately, some of the borders do not appear correct on some terminals. I have only been able to test it on the built in terminal that vscode has and the built in macos terminal of which it didnt work on very well.")
testbox.print()

