import phwd
import importlib
import textbox
def testphwd():
    importlib.reload(phwd)
    phwdm = phwd.getdailydata("dbg")
    print("Testing getting all data")
    data = phwdm.getalldata(72551594947, supressoutput=True)
    phwdm.cscreen()
    print("Sucess")
    phwdm.cleanup()
    print("cleaned all downloaded data")
    print("Testing getting data from range")
    data = phwdm.getdatafromrange(72551594947, 2017, 2020)
    phwdm.cscreen()
    print("Sucess")
    phwdm.cleanup()
    print("Getting data from year")
    data = phwdm.getdatafromyear(72551594947, 2020)
    phwdm.cscreen()
    print("Sucess")
    phwdm.cleanup()
def testtbox():
    importlib.reload(textbox)
    testbox = textbox.box()
    testbox.addtext("This is a test of the textbox.py module.")
    testbox.addtext("la de da do this is a test")
    testbox.print()
    testbox = textbox.box()
    testbox.addtext("This is a test of the textbox.py module.")
    testbox.addtext("la de da do this is a test")
    testbox.addtext("This is a very long line that will be wrapped.")
    testbox.addtext("Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.")
    testbox.print()
    testbox = textbox.box()
    testbox.addtext("This is a test of the textbox.py module.")
    testbox.addtext("la de da do this is a test")
    testbox.addtext("This is a very long line to test word wrapping with zero spaces.")
    testbox.addtext("12345678910111213141516171819202123242526272829348190481409179047109847901387409837091483709871093487094871098734109870398279084")
    testbox.print()
    testbox = textbox.box()
    testbox.addtext("This is a test of the textbox.py module.")
    testbox.addtext("la de da do this is a test")
    testbox.addtext("This is a very long line to test word wrapping with one space at the start.")
    testbox.addtext("This currently has a kind of dogey solution, but it works.")
    testbox.addtext("long line12345678910111213141516171819202123242526272829348190481409179047109847901387409837091483709871093487094871098734109870398279084")
    testbox.print()
    testbox = textbox.box(full=True)
    testbox.addtext("This tests the box being full, even with a little text")
    testbox.print()
    testbox = textbox.box(margin=5, full=True)
    testbox.addtext("this test has the full flag and a margin of 5")
    testbox.addtext("Hello World")
    testbox.print()
    testbox = textbox.box(margin=5, full=True, drawers=textbox.BLOCKDRAWERS)
    testbox.addtext("This is a text box with block sides")
    testbox.addtext("this looks weird imo")
    testbox.print()
    testbox = textbox.box(margin=5, full=True, drawers=textbox.SINGLEDRAWERS)
    testbox.addtext("This is a text box with single line sides")
    testbox.print()
    testbox = textbox.box(margin=5, full=True, drawers=textbox.THINDRAWERS)
    testbox.addtext("This is a text box with SKINNY SIDES")
    testbox.addtext("this made me add 2 sides for top and bottom lol")
    testbox.print()
    testbox = textbox.box(margin=5, full=True, drawers=textbox.OUTWARDTHINDRAWERS)
    testbox.addtext("This is a text box with OUTWARD SKINNY SIDES")
    testbox.addtext("this made me add 2 sides for top and bottom lol")
    testbox.print()
    testbox = textbox.box(margin=5, full=True)
    testbox.addtext("You can also change the default drawers by using textbox.defaultdrawers = new drawers")
    testbox.print()
def phwdinputtest():
    importlib.reload(phwd)
    phwdm = phwd.getdailydata("dbg")
    phwdm.usrinput()


